theme: jekyll-theme-dinky
title: John Chen | BSc. EE Student
description: This site was created to display the projects I have worked on, as well as compile useful links for myself and others.
google_analytics: UA-114721579-1